stages:
    - build-image

build:
    image: tmaier/docker-compose:latest
    stage: build-image
    services:
        - docker:dind
    tags:
        - docker
    script:
        - echo $GITLAB_ACCESS_TOKEN
        - echo $GITLAB_USER
        - echo $GITLAB_PASSWORD
        - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PASSWORD
        - docker-compose build
        - docker push registry.gitlab.com/macducks/express-angular:$CI_COMMIT_TAG
    only:
        - tags
    except:
        - branches